[project]
name = "og-agent-chat"
version = "0.1.5"
requires-python = ">=3.11"
dependencies = [
  "dspy-ai>=3.1.3",
  "prime-sandboxes>=0.2.15",
  "prime>=v0.5.40",
  "trackio>=0.15.0",
  "unidiff>=0.7.5",
]
